app/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, current_user
from app.utils.db_connection import get_db_connection_and_cursor
from app.models.models import User  # User modelini tanımlayacağız
from werkzeug.security import check_password_hash, generate_password_hash

auth_bp = Blueprint('auth_bp', __name__, url_prefix='/auth')

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.home'))

    form_type = request.args.get('form', 'login')
    
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        try:
            with get_db_connection_and_cursor() as (conn, cursor):
                cursor.execute("SELECT * FROM users WHERE username = %s", (username,))
                user_data = cursor.fetchone()
        except Exception as e:
            flash('Veritabanı hatası: ' + str(e), 'danger')
            return render_template('login.html', form_type='login', hide_navigation=True)

        if user_data and check_password_hash(user_data['password'], password):
            user = User(user_data)
            login_user(user)
            flash('Giriş başarılı!', 'success')
            next_page = request.args.get('next') # Kullanamadım bunu çünkü çalışmadı ama bir ara yapmamız lazım.
            # Hangi ekrandan login olma tuşuna bastıysak, login olduktan sonra o ekrana bizi geri döndürmesi lazım.
            return redirect(url_for('main_bp.auth_home')) # Şimdilik şarkılar ekranına döndürüyor.
        else:
            flash('Kullanıcı adı veya şifre hatalı.', 'danger')

    return render_template('login.html', form_type=form_type, hide_navigation=True)


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.home'))

    form_type = request.args.get('form', 'register')

    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        hashed_password = generate_password_hash(password, method='pbkdf2:sha256')
        
        try:
            with get_db_connection_and_cursor() as (conn, cursor):
                cursor.execute("SELECT * FROM users WHERE username = %s", (username,))
                existing_user = cursor.fetchone()
                
                if existing_user:
                    flash('Bu kullanıcı adı zaten alınmış. Lütfen farklı bir kullanıcı adı deneyin.', 'danger')
                    return render_template('login.html', form_type='register', hide_navigation=True)
                
                cursor.execute("INSERT INTO users (username, password) VALUES (%s, %s)", (username, hashed_password))
                conn.commit()
                flash('Kayıt başarılı! Giriş yapabilirsiniz.', 'success')
                return redirect(url_for('auth_bp.login', form='login'))
        except Exception as e:
            conn.rollback()
            flash('Kayıt sırasında bir hata oluştu.', 'danger')

    return render_template('login.html', form_type=form_type, hide_navigation=True)

@auth_bp.route('/logout')
def logout():
    if current_user.is_authenticated:
        logout_user()
        flash('Başarıyla çıkış yaptınız.', 'success')
    return redirect(url_for('main_bp.home'))

app/routes/favorites.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, current_user
from app.utils.db_connection import get_db_connection_and_cursor

fav_bp = Blueprint('fav_bp', __name__, url_prefix='/favorites')

@fav_bp.route('/songs')
@login_required
def favorite_songs():
    selected_page = 'songs'
    with get_db_connection_and_cursor() as (conn, cursor):
        query = """
        SELECT
            bp_track.track_id,
            bp_track.title AS song_title,
            MIN(bp_artist.artist_name) AS artist_name,  -- İlk sanatçıyı seçiyoruz
            MIN(artist_track.artist_id) AS artist_id   -- İlgili artist_id'yi seçiyoruz
        FROM
            favorite_tracks as ft
        INNER JOIN
            bp_track ON ft.track_id = bp_track.track_id
        INNER JOIN
            artist_track ON bp_track.track_id = artist_track.track_id
        INNER JOIN
            bp_artist ON artist_track.artist_id = bp_artist.artist_id
        WHERE
            ft.user_id = %(user_id)s
        GROUP BY
            bp_track.track_id, bp_track.title;
        """
        cursor.execute(query, {'user_id': current_user.id})
        track_rows = cursor.fetchall()

    # if not track_rows:
    #     return "No tracks found for this user.", 404

    tracks = []
    for row in track_rows:
        tracks.append({
            "track_id": row['track_id'],
            "title": row['song_title'],
            "artist_name": row['artist_name'],
            "artist_id": row['artist_id']
        })

    return render_template('fav.html', tracks=tracks, selected_page=selected_page)



@fav_bp.route('/albums')
@login_required
def favorite_albums():
    selected_page = 'releases'
    with get_db_connection_and_cursor() as (conn, cursor):
        query = """
        SELECT
            br.release_id,
            br.release_title,
            GROUP_CONCAT(DISTINCT ba.artist_name ORDER BY ba.artist_name SEPARATOR ', ') AS artist_names,
            GROUP_CONCAT(DISTINCT ar.artist_id ORDER BY ar.artist_id SEPARATOR ', ') AS artist_ids
        FROM
            favorite_albums fa
        INNER JOIN
            bp_release br ON fa.album_id = br.release_id
        INNER JOIN
            artist_release ar ON br.release_id = ar.release_id
        INNER JOIN
            bp_artist ba ON ar.artist_id = ba.artist_id
        WHERE
            fa.user_id = %s
        GROUP BY
            br.release_id, br.release_title
        """
        cursor.execute(query, (current_user.id,))
        favorite_albums_list = cursor.fetchall()
        
    return render_template('fav.html', selected_page=selected_page, albums=favorite_albums_list)


@fav_bp.route('/artists')
@login_required
def favorite_artists():
    selected_page = 'artists'
    with get_db_connection_and_cursor() as (conn, cursor):
        query = """
        SELECT
            bp_artist.artist_id,
            bp_artist.artist_name,
            bp_artist.artist_url
        FROM
            favorite_artists
        INNER JOIN
            bp_artist ON favorite_artists.artist_id = bp_artist.artist_id
        WHERE
            favorite_artists.user_id = %s
        """
        cursor.execute(query, (current_user.id,))
        favorite_artists_list = cursor.fetchall()
    # if not favorite_artists_list:
    #     return "No Favorite artists found",404 

    artists=[]
    for row in favorite_artists_list:
        artists.append({
            "artist_id": row['artist_id'],
            "artist_name": row['artist_name']
        })

        
    return render_template('fav.html', selected_page=selected_page, artists=favorite_artists_list)

app/templates/partials/footer.html
<footer class="footer">
    <p>© 2024 golet 11. All rights reserved.</p>
</footer>

app/templates/partials/header.html
<header style="display: flex; justify-content: space-between; align-items: center; margin-top: 20px;">
    <h1 class="header-title" style="margin: 0 auto;">Beatport Music</h1>
    <div style="display: flex; gap: 20px; margin-right: 13px">
        {% if current_user.is_authenticated %}
            <!-- Logout Button -->
            <a href="{{ url_for('auth_bp.logout') }}">
                <button type="button" class="btn btn-danger btn-lg" style="padding: 5px; width: 120px;">Log out</button>
            </a>
        {% else %}
            <!-- Log in and Sign up Buttons -->
            <a href="{{ url_for('auth_bp.login', next=request.url) }}">
                <button type="button" class="btn btn-primary btn-lg" style="padding: 5px; width: 120px; background-color: #333;">Log in</button>
            </a>
            <a href="{{ url_for('auth_bp.register', next=request.url) }}">
                <button type="button" class="btn btn-secondary btn-lg" style="padding: 5px; width: 120px;">Sign up</button>
            </a>
        {% endif %}
    </div>
</header>

app/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <!-- Home tuşu bir buton olarak değiştirildi -->
        {% if current_user.is_authenticated %}
            <a class="btn btn-primary btn-sm" href="{{ url_for('main_bp.auth_home') }}" style="margin-right: 50px;">Home</a>
        {% else %}
            <a class="btn btn-primary btn-sm" href="{{ url_for('main_bp.home') }}" style="margin-right: 50px;">Home</a>
        {% endif %}

        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="gap: 50px;">
                <li class="nav-item">
                    <a class="nav-link {% if request.endpoint == 'main_bp.songs' %}fw-bold{% endif %}" 
                       aria-current="page" href="{{ url_for('main_bp.songs') }}">Şarkılar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.endpoint == 'main_bp.albums' %}fw-bold{% endif %}" 
                       href="{{ url_for('main_bp.albums') }}">Albümler</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.endpoint == 'main_bp.artists' %}fw-bold{% endif %}" 
                       href="{{ url_for('main_bp.artists') }}">Sanatçılar</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {% if request.endpoint.startswith('fav_bp') %}fw-bold{% endif %}" 
                       role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Favoriler
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ url_for('fav_bp.favorite_songs') }}">Şarkılar</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('fav_bp.favorite_albums') }}">Albümler</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('fav_bp.favorite_artists') }}">Sanatçılar</a></li>
                    </ul>
                </li> 
            </ul>
            
            <form class="d-flex" role="search" method="GET" action="{{ url_for('main_bp.search') }}">
                <!-- Arama kelimesi için input -->
                <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
                <!-- Hangi sayfada arama yapacağız? (songs, artists, albums) -->
                <input type="hidden" name="selected_page" value="{{ selected_page }}">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>